[package]
name = "blind-ldap-extraction-THM"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart", "cookies"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.16"
